/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sparta_helmet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HelmetModel(props) {
  const { nodes, materials } = useGLTF('/models/sparta_helmet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_cb107c9c-f5e1-4e04-85da-faac169a3194'].geometry} material={materials['tripo_material_cb107c9c-f5e1-4e04-85da-faac169a3194']} />
    </group>
  )
}

useGLTF.preload('/models/sparta_helmet.glb')
