/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sparta_helmet.glb 
Author: Adriancgmask (https://sketchfab.com/Adriancgmask)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sparta-helmet-e8d501c7729246fd92d55083d80d8cbb
Title: SPARTA HELMET
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HelmetModel(props) {
  const { nodes, materials } = useGLTF('/models/sparta_helmet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sparta_low_sparta_low_0.geometry} material={materials.sparta_low} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/sparta_helmet.glb')
