/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shield.glb 
Author: The Parabox (https://sketchfab.com/mariamorain)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spartan-shield-cycles-pbr-test-9d602ea6605b4929ba5cdcf1e2353576
Title: Spartan shield Cycles PBR test
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ShieldModel(props) {
  const { nodes, materials } = useGLTF('/models/shield.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lp_Material003_0.geometry} material={materials['Material.003']} position={[-33.019, 228.463, 1785.12]} rotation={[-1.67, -0.041, 0.779]} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/shield.glb')
