/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sword.glb 
Author: kozachoks (https://sketchfab.com/kozachoks)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/spartan-sword-low-poly-f281ac6dc3d64b0288fe1ddc2d71637f
Title: Spartan_sword (low_poly)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SwordModel(props) {
  const { nodes, materials } = useGLTF('/models/sword.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sword_lp002_HH_Sword_blade_0.geometry} material={materials.HH_Sword_blade} rotation={[2.823, 0, 0.236]} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/sword.glb')
