/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 trophy.glb 
Author: Incg5764 (https://sketchfab.com/incg5764)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golden-trophy-79389eecca164e27a75d362fbbecfe3b
Title: Golden Trophy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TrophyModel(props) {
  const { nodes, materials } = useGLTF('/models/trophy.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/trophy.glb')
